[tox]
minversion = 1.8
basepython = python3
skipsdist = true
envlist = py3-molecule-podman

[testenv]
passenv = *
deps =
    molecule<4.0
    molecule-podman
    ansible<5.0
    jmespath
    selinux
    lxml

[testenv:molecule-podman]
commands =
    molecule test -s compatibility --destroy always